// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6e2ho1wRg4yjJyISTc199ZoT4nQbv5LM',
    appId: '1:121986177636:web:38cb7693803aaed87f1d71',
    messagingSenderId: '121986177636',
    projectId: 'final-project-d42e1',
    authDomain: 'final-project-d42e1.firebaseapp.com',
    storageBucket: 'final-project-d42e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsv00szICTATe3VZ4SwmSZMhU6gIg_ufo',
    appId: '1:121986177636:android:3e748a265c564ebd7f1d71',
    messagingSenderId: '121986177636',
    projectId: 'final-project-d42e1',
    storageBucket: 'final-project-d42e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60GMmhdHrbcTDn_DgLz2Vj3WbLBHWFZY',
    appId: '1:121986177636:ios:e3b2f062bc1a77417f1d71',
    messagingSenderId: '121986177636',
    projectId: 'final-project-d42e1',
    storageBucket: 'final-project-d42e1.firebasestorage.app',
    iosBundleId: 'com.example.helperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60GMmhdHrbcTDn_DgLz2Vj3WbLBHWFZY',
    appId: '1:121986177636:ios:e3b2f062bc1a77417f1d71',
    messagingSenderId: '121986177636',
    projectId: 'final-project-d42e1',
    storageBucket: 'final-project-d42e1.firebasestorage.app',
    iosBundleId: 'com.example.helperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6e2ho1wRg4yjJyISTc199ZoT4nQbv5LM',
    appId: '1:121986177636:web:e3ce8e5554c8e5227f1d71',
    messagingSenderId: '121986177636',
    projectId: 'final-project-d42e1',
    authDomain: 'final-project-d42e1.firebaseapp.com',
    storageBucket: 'final-project-d42e1.firebasestorage.app',
  );
}
